--CREATE DATABASE plateformesupportbdd ;
--GO
USE plateformesupportbdd;

CREATE TABLE PERSONNES (
	NOM varchar(40),
	PRENOM varchar(40),
	ID uniqueidentifier,
	CONSTRAINT pk_personnes PRIMARY KEY (ID)
)

CREATE TABLE SALARIES (
	ID_SALARIE uniqueidentifier,
	LOG_IN varchar(30) UNIQUE,
	PWD varchar(15),
	PRESENCE bit DEFAULT 0,
	JOUR smallint,
	CONSTRAINT pk_salaries PRIMARY KEY (ID_SALARIE),
	CONSTRAINT fk_salaries_personnes FOREIGN KEY (ID_SALARIE) REFERENCES PERSONNES(ID),
	CONSTRAINT ck_jour_salaries CHECK (JOUR BETWEEN 1 AND 5)
)

CREATE TABLE CLIENTS (
	ID_CLIENT uniqueidentifier,
	TELEPHONE CHAR(10),
	MAIL varchar(60),
	CONSTRAINT pk_clients PRIMARY KEY (ID_CLIENT),
	CONSTRAINT fk_clients_personnes FOREIGN KEY (ID_CLIENT) REFERENCES PERSONNES(ID)
)
ALTER TABLE CLIENTS ADD CONSTRAINT ck_mail_clients CHECK (MAIL LIKE '%@%.%');

CREATE TABLE PROFILS (
	ID_PROFIL uniqueidentifier,
	USERSTATUS CHAR(3),
	CONSTRAINT pk_profils PRIMARY KEY (ID_PROFIL),
	CONSTRAINT fk_profils_salaries FOREIGN KEY (ID_PROFIL) REFERENCES SALARIES(ID_SALARIE),
	CONSTRAINT ck_userstatus_profils CHECK (USERSTATUS IN ('ADM','CNS','ACC'))
)

CREATE TABLE RENDEZVOUS (
	ID_SALARIE uniqueidentifier,
	ID_CLIENT uniqueidentifier,
	JOURRDV date,
	PARTIEJOURRDV char(3),
	CONSTRAINT pk_rendezvous PRIMARY KEY (ID_SALARIE, ID_CLIENT),
	CONSTRAINT fk_rendezvous_salaries FOREIGN KEY (ID_SALARIE) REFERENCES SALARIES(ID_SALARIE),
	CONSTRAINT fk_rendezvous_clients FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT),
	CONSTRAINT ck_partiejourrdv_rendezvous CHECK (PARTIEJOURRDV IN ('MAT','APR'))
)