USE plateformesupportbdd;

INSERT INTO PERSONNES(NOM, PRENOM, ID) VALUES ('AUGEL','Kévin', newid());
INSERT INTO PERSONNES(NOM, PRENOM, ID) VALUES ('DUPOND','Jean', newid());
INSERT INTO PERSONNES(NOM, PRENOM, ID) VALUES ('DUPONT','Michel', newid());
INSERT INTO PERSONNES(NOM, PRENOM, ID) VALUES ('DOE','John', newid());
INSERT INTO PERSONNES(NOM, PRENOM, ID) VALUES ('DOE','Jane', newid());
INSERT INTO PERSONNES(NOM, PRENOM, ID) VALUES ('GAUTHIER','Charles', newid());

INSERT INTO SALARIES(ID_SALARIE, LOG_IN, PWD) VALUES (
	(SELECT ID FROM PERSONNES WHERE NOM LIKE 'AUGEL' AND PRENOM LIKE 'Kévin'),
	(SELECT LEFT(PRENOM,1) FROM PERSONNES WHERE NOM LIKE 'AUGEL' AND PRENOM LIKE 'Kévin')+(SELECT LEFT(NOM,10) FROM PERSONNES WHERE NOM LIKE 'AUGEL' AND PRENOM LIKE 'Kévin'),
	'root'
);
INSERT INTO SALARIES(ID_SALARIE, LOG_IN, PWD, JOUR) VALUES (
	(SELECT ID FROM PERSONNES WHERE NOM LIKE 'DUPOND' AND PRENOM LIKE 'Jean'),
	(SELECT LEFT(PRENOM,1) FROM PERSONNES WHERE NOM LIKE 'DUPOND' AND PRENOM LIKE 'Jean')+(SELECT LEFT(NOM,10) FROM PERSONNES WHERE NOM LIKE 'DUPOND' AND PRENOM LIKE 'Jean'),
	'Lundi',
	1
);
INSERT INTO SALARIES(ID_SALARIE, LOG_IN, PWD, JOUR) VALUES (
	(SELECT ID FROM PERSONNES WHERE NOM LIKE 'DUPONT' AND PRENOM LIKE 'Michel'),
	(SELECT LEFT(PRENOM,1) FROM PERSONNES WHERE NOM LIKE 'DUPONT' AND PRENOM LIKE 'Michel')+(SELECT LEFT(NOM,10) FROM PERSONNES WHERE NOM LIKE 'DUPONT' AND PRENOM LIKE 'Michel'),
	'Mardi',
	2
);
INSERT INTO SALARIES(ID_SALARIE, LOG_IN, PWD, JOUR) VALUES (
	(SELECT ID FROM PERSONNES WHERE NOM LIKE 'DOE' AND PRENOM LIKE 'John'),
	(SELECT LEFT(PRENOM,1) FROM PERSONNES WHERE NOM LIKE 'DOE' AND PRENOM LIKE 'John')+(SELECT LEFT(NOM,10) FROM PERSONNES WHERE NOM LIKE 'DOE' AND PRENOM LIKE 'John'),
	'Mercredi',
	3
);
INSERT INTO SALARIES(ID_SALARIE, LOG_IN, PWD, JOUR) VALUES (
	(SELECT ID FROM PERSONNES WHERE NOM LIKE 'DOE' AND PRENOM LIKE 'Jane'),
	(SELECT LEFT(PRENOM,2) FROM PERSONNES WHERE NOM LIKE 'DOE' AND PRENOM LIKE 'Jane')+(SELECT LEFT(NOM,10) FROM PERSONNES WHERE NOM LIKE 'DOE' AND PRENOM LIKE 'Jane'),
	'Jeudi',
	4
);
INSERT INTO SALARIES(ID_SALARIE, LOG_IN, PWD, JOUR) VALUES (
	(SELECT ID FROM PERSONNES WHERE NOM LIKE 'GAUTHIER' AND PRENOM LIKE 'Charles'),
	(SELECT LEFT(PRENOM,1) FROM PERSONNES WHERE NOM LIKE 'GAUTHIER' AND PRENOM LIKE 'Charles')+(SELECT LEFT(NOM,10) FROM PERSONNES WHERE NOM LIKE 'GAUTHIER' AND PRENOM LIKE 'Charles'),
	'Vendredi',
	5
);

INSERT INTO PERSONNES(NOM, PRENOM, ID) VALUES ('PUTIN','Serj', newid());
INSERT INTO PERSONNES(NOM, PRENOM, ID) VALUES ('GARNO','Mathieu', newid());

INSERT INTO CLIENTS(ID_CLIENT, TELEPHONE, MAIL) VALUES (
	(SELECT ID FROM PERSONNES WHERE NOM LIKE 'PUTIN' AND PRENOM LIKE 'Serj'),
	'0668951543',
	'serj.putin@glados.ru'
)
INSERT INTO CLIENTS(ID_CLIENT, TELEPHONE, MAIL) VALUES (
	(SELECT ID FROM PERSONNES WHERE NOM LIKE 'GARNO' AND PRENOM LIKE 'Mathieu'),
	'0251498562',
	'MathieuG@minis.org.com'
)

SELECT * FROM PERSONNES WHERE 1=1;
SELECT * FROM SALARIES WHERE 1=1 ;
SELECT * FROM CLIENTS WHERE 1=1;

--DELETE FROM PERSONNES WHERE 1=1;
--DELETE FROM SALARIES WHERE 1=1;
--DELETE FROM CLIENTS WHERE 1=1;
