/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tosmont2016' at '04/04/17 10:58' with Gradle 2.14.1
 *
 * @author tosmont2016, @date 04/04/17 10:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
